# Generated by Django 5.2.1 on 2025-12-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0002_posocotablea_posocotableg_nrldc2adata_nrldc2cdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRLDC3BData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(blank=True, null=True)),
                ('reporting_datetime', models.DateTimeField(blank=True, null=True)),
                ('station', models.TextField()),
                ('installed_capacity_mw', models.IntegerField(blank=True, null=True)),
                ('peak_1900_mw', models.IntegerField(blank=True, null=True)),
                ('offpeak_0300_mw', models.IntegerField(blank=True, null=True)),
                ('day_peak_mw', models.IntegerField(blank=True, null=True)),
                ('day_peak_hrs', models.CharField(blank=True, max_length=64, null=True)),
                ('day_energy_mu', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('avg_mw', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('row_type', models.CharField(blank=True, max_length=32, null=True)),
                ('source_page', models.IntegerField(blank=True, null=True)),
                ('source_table_index', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('station', 'report_date')},
            },
        ),
    ]
