# Generated by Django 5.2.8 on 2025-12-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0003_srldc3bdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='srldc3bdata',
            old_name='day_energy_mu',
            new_name='gross_energy_mu',
        ),
        migrations.AlterUniqueTogether(
            name='srldc3bdata',
            unique_together={('report_date', 'station')},
        ),
        migrations.AddField(
            model_name='srldc3bdata',
            name='min_generation_hrs',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='srldc3bdata',
            name='min_generation_mw',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='srldc3bdata',
            name='net_energy_mu',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
    ]
