# Generated by Django 5.2.8 on 2025-12-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0004_rename_day_energy_mu_srldc3bdata_gross_energy_mu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='srldc3bdata',
            name='min_generation_hrs',
        ),
        migrations.RemoveField(
            model_name='srldc3bdata',
            name='min_generation_mw',
        ),
        migrations.AddField(
            model_name='srldc3bdata',
            name='day_energy_mu',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
    ]
