# Generated by Django 5.2.8 on 2025-12-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0005_remove_srldc3bdata_min_generation_hrs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='srldc3bdata',
            name='day_energy_mu',
        ),
        migrations.AddField(
            model_name='srldc3bdata',
            name='min_generation_hrs',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='srldc3bdata',
            name='min_generation_mw',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
